
server:
  port: ${EUREKA_PORT:9999}
  servlet:
    context-path: /
    application-display-name: ${spring.application.name}

eureka:
  instance:
    hostname: gitlab.bryce.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://gitlab.bryce.com:${server.port}/eureka/