logging:
  level:
    fun.bryce: debug
server:
  port: ${EUREKA_PORT:8888}
  servlet:
    context-path: /
    application-display-name: ${spring.application.name}
eureka:
  instance:
    hostname: gitlab.bryce.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://gitlab.bryce.com:9999/eureka/